

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
        automerged: false
        requires:
          pushes: true
        updates:
          - commit-message:
              prefix: "chore: "
              extends: ["@commitlint/config-conventional"]
