name: CHECK_MERGE

on:
  push:
    branches: [main]

jobs:
  CHECK_ALL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: CHECK ALL
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Lint commits
        run: npx commitlint --from ${{ github.event.push.base.sha }} --to ${{ github.event.push.head.sha }} --verbose
        
      - name: 'run test'
        run: npm run test
    
  MERGE:
    needs: CHECK_ALL
    runs-on: ubuntu-latest
    environment: MERGE
    steps:
    - name: MERGE
      run: deploy.sh
      if: ${{ needs.CHECK_ALL.result == 'success' }}      

