name: CHECK_MERGE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CHECK_ALL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: CHECK ALL
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: 'run test'
        run: npm run test
      - name: Check commit prefixes
        run: |
          if git log --format=%B -n 1 ${{ github.sha }} | grep -E '^(fix|feat|docs|style|refactor|test|chore):' ; then
            echo "Commit message has valid prefix"
          else
            echo "Commit message does not have valid prefix"
            exit 1
          fi


