name: CHECK_MERGE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CHECK_ALL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: CHECK ALL
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Lint commits
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git log --pretty=format:'%H' ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tac | xargs -I % sh -c 'if [ "$1" == "%" ]; then exit 1; fi; git log --pretty=format:"%H" -n 1 $1..%; npx commitlint --from=$1 --to=% --verbose' -- ${{ github.event.pull_request.base.sha }}
          else
            npx commitlint --from ${{ github.event.push.base.sha }} --to ${{ github.event.push.head.sha }} --verbose
          fi

      - name: 'run test'
        run: npm run test
    


