name: CI

on:
  push:
    branches: [main]

jobs:
  TESTS:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: TESTS
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Lint commits
        run: npx commitlint --from ${{ github.event.push.base.sha }} --to ${{ github.event.push.head.sha }} --verbose
        
      - name: 'run test'
        run: npm run test
        
      - name: Deploy
        run: deploy.sh
        if: success()
