name: CHECK_MERGE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CHECK_ALL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: CHECK ALL
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        
      - name: Lint commits
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin pull/${{ github.event.pull_request.number }}/head
            git fetch origin pull/${{ github.event.pull_request.number }}/merge
            BASE=$(git merge-base FETCH_HEAD FETCH_HEAD^)
            npx commitlint --from ${BASE} --to FETCH_HEAD --verbose
          else
            npx commitlint --from ${{ github.event.push.base.sha }} --to ${{ github.event.push.head.sha }} --verbose
          fi
        
      - name: 'run test'
        run: npm run test
    


