name: CHECK_MERGE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CHECK_ALL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: CHECK ALL
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Check commit prefixes in PR
        run: |
          for commit in $(git rev-list --no-merges HEAD ^${{ github.base_ref }}); do
            if ! git log --format=%B -n 1 $commit | grep -E '^(fix|feat|docs|style|refactor|test|chore):' ; then
              echo "Commit $commit does not have valid prefix"
              exit 1
            fi
          done


